- name: install sudo, vim, .vimrc, add my user to sudoers, and install open-vm-tools
  remote_user: root
  hosts: all

  tasks:
      - name: install sudo
        apt:
            name: sudo
            update_cache: yes

      - name: add tyler to sudoers
        user:
            name: tyler
            groups: sudo
            append: yes

      - name: install vim
        apt:
            name: vim

      - name: install open-vm-tools
        apt:
            name: open-vm-tools

      - name: install git
        apt:
            name: git

      - name: pull vimrc from git
        become: yes
        become_user: tyler
        git:
            dest: /home/tyler/.vim_runtime
            repo: 'https://github.com/amix/vimrc.git'
            depth: 1

      - name: install basic vimrc
        become: yes
        become_user: tyler
        copy:
            src: /home/tyler/.vim_runtime/vimrcs/basic.vim
            dest: /home/tyler/.vimrc
