- name: configure a gitlab runner node on Debian 10
  remote_user: root
  hosts: all
  environment:
      GITLAB_RUNNER_DISABLE_SKEL: true
  vars_files:
      - secrets/keys.yml

  tasks:
      - name: ensure tools are installed
        apt:
            pkg:
                - curl
                - gnupg
                - debian-archive-keyring
                - apt-transport-https
                - python-pip

      - name: install python gitlab api
        pip:
            name: python-gitlab

      - name: add gpg key
        apt_key:
            url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey 
            state: present

      - name: add package repo
        apt_repository:
            repo: deb https://packages.gitlab.com/runner/gitlab-runner/debian/ buster main
            state: present

      - name: add src repo
        apt_repository:
            repo: deb-src https://packages.gitlab.com/runner/gitlab-runner/debian/ buster main
            state: present

      - name: update apt cache
        apt:
            update-cache: yes

      - name: copy APT pinning file to ensure gitlab repo used
        copy:
            src: "{{ playbook_dir }}/conf/pin-gitlab-runner.pref"
            dest: /etc/apt/preferences.d/pin-gitlab-runner.pref

      - name: install gitlab runner package
        apt:
            name: gitlab-runner

      - name: register runner
        #no_log: True
        community.general.gitlab_runner:
            api_url: "{{ gitlab_url }}"
            registration_token: "{{ gitlab_runner_token }}"
            api_token: "{{ gitlab_api_token }}"
            description: Debian
            active: True
            tag_list: ['debian', 'linux']
            run_untagged: True
            locked: False
            state: present

      - name: modify runner config to use shell executor
        lineinfile:
            path: /etc/gitlab-runner/config.toml
            regexp: '^executor ='
            line: executor = shell
